version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./Enoki"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "./Enoki/src-tauri"
    schedule:
      interval: "daily"