/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Shiitake */

#ifndef _Included_Shiitake
#define _Included_Shiitake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Shiitake
 * Method:    init_measurements
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Shiitake_init_1measurements
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    cpu_usage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Shiitake_cpu_1usage
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    cpu_frequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Shiitake_cpu_1frequency
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    memory_usage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Shiitake_memory_1usage
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    network_usage_in
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Shiitake_network_1usage_1in
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    network_usage_out
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Shiitake_network_1usage_1out
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    os_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Shiitake_os_1version
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    cpu_cores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Shiitake_cpu_1cores
  (JNIEnv *, jclass);

/*
 * Class:     Shiitake
 * Method:    memory_total
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Shiitake_memory_1total
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
